eureka:
  instance:
    prefer-ip-address:  true
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost
spring:
  application:
    name: Config-Default
    
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
