eureka:
  instance:
    prefer-ip-address:  true
    
  eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8888/eureka
spring:
  application:
    name: Config-Default
    
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
