eureka:
  instance:
    prefer-ip-address:  false
  
eureka:
  client:
   instance:
    hostname: localhost
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
spring:
  application:
    name: Config-Prod
    
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
