eureka:
  instance:
    prefer-ip-address:  false
  
eureka:
  client:
   instance:
    hostname: localhost
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/
 
spring:
  application:
    name: Config-Default
    
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
