eureka:
  instance:
    prefer-ip-address:  true
    
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      uri: http://localhost:8086
  config:
    activate:
      on-profile:
        active:native
