eureka:
  instance:
    prefer-ip-address:  true
    
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${http://127.0.0.1:8762/eureka}
    instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
spring:
  application:
    name: CONFIG-SERVER
    
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
